# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_zakaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 17, 16, 48, 10, 937157), verbose_name='Time'),
        ),
    ]
