# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160119_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 12, 4, 50, 645193), verbose_name='Time'),
        ),
    ]
