# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20160120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 16, 17, 46, 6832), verbose_name='Time'),
        ),
    ]
