# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160121_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 20, 2, 14, 330170), verbose_name='Time'),
        ),
    ]
