# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20160121_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('permissions', models.CharField(default='USER', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 20, 43, 25, 365954), verbose_name='Time'),
        ),
    ]
