# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20160122_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 1, 50, 17, 292591), verbose_name='Time'),
        ),
    ]
