# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20160122_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Lud', 'verbose_name_plural': 'Ludi'},
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 2, 3, 44, 858533), verbose_name='Time'),
        ),
    ]
