# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20160122_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of bootik')),
                ('alias', models.SlugField(verbose_name='Alias bootik')),
            ],
            options={
                'verbose_name': 'Botik',
                'verbose_name_plural': 'Bootiki',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=46, max_length=20, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default=123, max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 2, 6, 37, 396323), verbose_name='Time'),
        ),
    ]
