# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20160122_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 2, 15, 30, 794788), verbose_name='Time'),
        ),
    ]
