# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20160122_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 22, 8, 47, 21, 349643), verbose_name='Time'),
        ),
    ]
